import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Aizaz Ahmad Saifi',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'user',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Mobile',
      slug: 'Mobile',
      category: 'Electronics',
      image: '/images/mobile.jpg',
      price: 70,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular mobile',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'T-Shirt',
      slug: 't-shirt',
      category: 'Apparel',
      image: '/images/shirt.jpg',
      price: 80,
      brand: 'Nike',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular T-shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Shoes',
      slug: 'shoes',
      category: 'Footwear',
      image: '/images/shoes.jpg',
      price: 90,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shoes',
    },
    {
      name: 'Laptop',
      slug: 'laptops',
      category: 'Electronics',
      image: '/images/laptop.jpg',
      price: 90,
      brand: 'Lenevo',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Best Laptop',
    },
    {
      name: 'Jeans',
      slug: 'fit-jeans',
      category: 'Apparel',
      image: '/images/jeans.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular Jeans',
    },
    {
      name: 'Watch',
      slug: 'watch',
      category: 'Electronics',
      image: '/images/watch.jpg',
      price: 75,
      brand: 'Apple',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular watch',
    },
  ],
};

export default data;
